name: celesteaustral
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#892d17'
    - '#e49725'
    - '#bc4917'
    - '#32190d'
    - '#fde473'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
