name: celesteaustral
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c5c0'
    - '#af8889'
    - '#fefefe'
    - '#3c211f'
    - '#86474a'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
